[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "shared_utils"
version = "0.1.0"
description = "Shared utilities for Inventory Management"
authors = [{ name = "Arun" }]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
