# =========================
# Inventory Management Service Config
# =========================
inventory_management:
  api:
    host: 0.0.0.0
    port: 8001

  logging:
    level: DEBUG
    log_file_path: logs/inventory.log

  cv_service:
    url: http://localhost:8000/predict
    model_path: /app/model/model_weights.pt
    train_data_path: /app/data/train
    valid_data_path: /app/data/valid

  event_queue:
    host: localhost
    port: 5672
    name: inventory_events
